### ISSUE TITLE
Fatal error: Call to a member function sqlStart() on a non-object in /home/oil/public_html/includes/php-profiler/profiler.php on line 315

### ISSUE THREAD

**Issue by davidmurdoch** [jimrubenstein/php-profiler#9]
I get this error: `Fatal error: Call to a member function sqlStart() on a non-object in /home/oil/public_html/includes/php-profiler/profiler.php on line 315` when running the following code on PHP 5.2.9:

```
require("php-profiler/profiler.php");
Profiler::enable();
$query = "SELECT * FROM `table`";
$queryProf = Profiler::sqlStart( $query );
// $dbi is a mysqli db connection, obviously.
$results = mysqli_query( $dbi, $query );
$queryProf->end();
```

**Comment by davidmurdoch** [comment]
It look slike `Profiler::start("something");` is required before calling sqlStart for the first time.

**Comment by jimrubenstein** [comment]
Thanks for the report @davidmurdoch.  I pushed a patch for this issue.  When you start a query node, now, the Profiler will check to see if there is currently a profiling node in the stack.  If there is no node on the stack, it creates a default one to put it in.
